ttranking/core/urls.py
# ttranking/core/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.APIRootView.as_view(), name='api_root'),
    path('token/', TokenObtainPairView.as_view(), name='api_token'),
    path('token-refresh/', TokenRefreshView.as_view(), name='api_token_refresh'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('admin/home/', views.AdminHomeView.as_view(), name='admin_home')
]

ttranking/players/urls.py
# ttranking/players/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PlayerViewSet, RankingViewSet, country_choices, ranking_integrity

app_name = 'players'

# Default routes for api consistency
router = DefaultRouter()
router.register(r'player', PlayerViewSet)
router.register(r'ranking', RankingViewSet)

# print(router.urls)

urlpatterns = [
    path('country-choices/', country_choices, name='country-choices'),
    path('ranking-integrity/', ranking_integrity, name='ranking-integrity'),
    path('', include(router.urls)),
]

ttranking/ttranking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler404, handler500
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('api/', include('core.urls')),
    path('api/players/', include('players.urls')),
    path('api/matches/', include('matches.urls')),
    path('api/seasons/', include('seasons.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttranking/players/models.py
# ttranking/players/models.py
from django.db import models
from django.core.files.base import ContentFile
from datetime import date
from PIL import Image
import io
import os
from uuid import uuid4
from typing import Tuple
from seasons.models import Season

# Define a tuple of tuples with country code and country name
COUNTRY_CHOICES = [
    ('AF', 'Afganistán'),
    ('AL', 'Albania'),
    ('DZ', 'Argelia'),
    ('AO', 'Angola'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaiyán'),
    ('BS', 'Bahamas'),
    ('BH', 'Baréin'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Bielorrusia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belice'),
    ('BJ', 'Benín'),
    ('BT', 'Bután'),
    ('BO', 'Bolivia'),
    ('BA', 'Bosnia y Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brasil'),
    ('BN', 'Brunéi'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('KH', 'Camboya'),
    ('CM', 'Camerún'),
    ('CA', 'Canadá'),
    ('CV', 'Cabo Verde'),
    ('CF', 'República Centroafricana'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('KM', 'Comoras'),
    ('CG', 'Congo'),
    ('CD', 'República Democrática del Congo'),
    ('CR', 'Costa Rica'),
    ('CI', 'Costa de Marfil'),
    ('HR', 'Croacia'),
    ('CU', 'Cuba'),
    ('CY', 'Chipre'),
    ('CZ', 'República Checa'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Yibuti'),
    ('DM', 'Dominica'),
    ('DO', 'República Dominicana'),
    ('EC', 'Ecuador'),
    ('EG', 'Egipto'),
    ('SV', 'El Salvador'),
    ('GQ', 'Guinea Ecuatorial'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('ET', 'Etiopía'),
    ('FJ', 'Fiyi'),
    ('FI', 'Finlandia'),
    ('FR', 'Francia'),
    ('GA', 'Gabón'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Alemania'),
    ('GH', 'Ghana'),
    ('GR', 'Grecia'),
    ('GD', 'Granada'),
    ('GT', 'Guatemala'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bisáu'),
    ('GY', 'Guyana'),
    ('HT', 'Haití'),
    ('HN', 'Honduras'),
    ('HU', 'Hungría'),
    ('IS', 'Islandia'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Irán'),
    ('IQ', 'Irak'),
    ('IE', 'Irlanda'),
    ('IL', 'Israel'),
    ('IT', 'Italia'),
    ('JM', 'Jamaica'),
    ('JP', 'Japón'),
    ('JO', 'Jordania'),
    ('KZ', 'Kazajistán'),
    ('KE', 'Kenia'),
    ('KI', 'Kiribati'),
    ('KP', 'Corea del Norte'),
    ('KR', 'Corea del Sur'),
    ('KW', 'Kuwait'),
    ('KG', 'Kirguistán'),
    ('LA', 'Laos'),
    ('LV', 'Letonia'),
    ('LB', 'Líbano'),
    ('LS', 'Lesoto'),
    ('LR', 'Liberia'),
    ('LY', 'Libia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituania'),
    ('LU', 'Luxemburgo'),
    ('MK', 'Macedonia del Norte'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malasia'),
    ('MV', 'Maldivas'),
    ('ML', 'Malí'),
    ('MT', 'Malta'),
    ('MH', 'Islas Marshall'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauricio'),
    ('MX', 'México'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldavia'),
    ('MC', 'Mónaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MA', 'Marruecos'),
    ('MZ', 'Mozambique'),
    ('MM', 'Birmania'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Países Bajos'),
    ('NZ', 'Nueva Zelanda'),
    ('NI', 'Nicaragua'),
    ('NE', 'Níger'),
    ('NG', 'Nigeria'),
    ('NO', 'Noruega'),
    ('OM', 'Omán'),
    ('PK', 'Pakistán'),
    ('PW', 'Palaú'),
    ('PS', 'Territorio Palestino Ocupado'),
    ('PA', 'Panamá'),
    ('PG', 'Papúa Nueva Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Perú'),
    ('PH', 'Filipinas'),
    ('PL', 'Polonia'),
    ('PT', 'Portugal'),
    ('QA', 'Catar'),
    ('RO', 'Rumania'),
    ('RU', 'Federación Rusa'),
    ('RW', 'Ruanda'),
    ('KN', 'San Cristóbal y Nieves'),
    ('LC', 'Santa Lucía'),
    ('VC', 'San Vicente y las Granadinas'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Santo Tomé y Príncipe'),
    ('SA', 'Arabia Saudita'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leona'),
    ('SG', 'Singapur'),
    ('SK', 'Eslovaquia'),
    ('SI', 'Eslovenia'),
    ('SB', 'Islas Salomón'),
    ('SO', 'Somalia'),
    ('ZA', 'Sudáfrica'),
    ('SS', 'Sudán del Sur'),
    ('ES', 'España'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudán'),
    ('SR', 'Surinam'),
    ('SZ', 'Suazilandia'),
    ('SE', 'Suecia'),
    ('CH', 'Suiza'),
    ('SY', 'Siria'),
    ('TW', 'Taiwán'),
    ('TJ', 'Tayikistán'),
    ('TZ', 'Tanzania'),
    ('TH', 'Tailandia'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad y Tobago'),
    ('TN', 'Túnez'),
    ('TR', 'Turquía'),
    ('TM', 'Turkmenistán'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ucrania'),
    ('AE', 'Emiratos Árabes Unidos'),
    ('GB', 'Reino Unido'),
    ('US', 'Estados Unidos'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistán'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabue'),
]

GENDER_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Femenino')
]

DESIRED_SIZE = (600, 600)

def get_image_upload_path(instance, filename):
    # Generate a new filename using the player's ID or a UUID
    if not filename:
        return None
    ext = instance.photo.name.split('.')[-1]
    new_filename = f'{instance.id or uuid4().hex}.{ext}'
    return os.path.join('player_photos/', new_filename)

class Player(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=False, blank=True, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=2, choices=COUNTRY_CHOICES, blank=True, null=True)
    photo = models.ImageField(upload_to=get_image_upload_path, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    @property
    def age(self) -> int:
        if self.date_of_birth is None:
            return None
        today = date.today()
        age = today.year - self.date_of_birth.year
        if (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day):
            age -= 1
        return age

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Step 1: Check if this is an update and get the old instance
        if self.pk:
            old_instance = Player.objects.filter(pk=self.pk).first()
            old_photo = old_instance.photo if old_instance else None
        else:
            old_photo = None

        # Step 2: Process the new photo only if it's updated
        if self.photo and (not old_photo or old_photo != self.photo):
            # Delete the old photo if a new one is being uploaded
            if old_photo and os.path.isfile(old_photo.path):
                os.remove(old_photo.path)

            # Generate a new unique path for the photo
            ext = self.photo.name.split('.')[-1]
            file_path = os.path.join('player_photos/', f'{uuid4().hex}.{ext}')

            # Open and process the image
            image = Image.open(self.photo)
            image = self.resize_and_crop(image, DESIRED_SIZE)

            # Save the processed image to a BytesIO object
            buffer = io.BytesIO()
            image.save(buffer, format='PNG')
            buffer.seek(0)

            # Save the resized image to the photo field
            self.photo.save(file_path, ContentFile(buffer.read()), save=False)

        # Step 3: Call the original save method to save the rest of the fields
        super(Player, self).save(*args, **kwargs)

        self.create_rankings()

    def create_rankings(self):
        # Step 4: Create the player rankings for all seasons
        Ranking.populate_ranking(self)

    def resize_and_crop(self, image, size):
        # Resize the image without preserving the aspect ratio
        image = image.convert('RGBA')
        image = image.resize(size)
        return image

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Ranking(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='season_rankings')
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='player_rankings')
    ranking = models.IntegerField(default=0)
    singles_matches_played = models.IntegerField(default=0)
    doubles_matches_played = models.IntegerField(default=0)
    doubles_victories = models.IntegerField(default=0)
    singles_victories = models.IntegerField(default=0)

    class Meta:
        unique_together = ('player', 'season')

    @property
    def matches_played(self):
        return self.singles_matches_played + self.doubles_matches_played

    @property
    def victories(self):
        return self.doubles_victories + self.singles_victories

    @property
    def winrate(self):
        if self.matches_played == 0:
            return 0
        return round((self.victories / self.matches_played) * 100, 2)

    def get_season_points(self, match_type: str) -> Tuple[int, int]:
        """
        Get the points for a win and a loss correspoding to the season assigned for the given match type
        (singles or doubles)
        :param match_type:
        :return:
        """
        if match_type not in ['singles', 'doubles']:
            raise ValueError("Invalid match type, must be 'singles' or 'doubles'")

        season = self.season
        if match_type == 'singles':
            return season.singles_points_for_win, season.singles_points_for_loss
        elif match_type == 'doubles':

ttranking/players/views.py
# ttrankin/players/views.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action, api_view
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, AllowAny
from rest_framework.pagination import PageNumberPagination
from .models import Player, Ranking, COUNTRY_CHOICES
from .serializers import PlayerSerializer, RankingSerializer

PLAYERS_PER_PAGE = 6

@api_view(['GET'])
def country_choices(request):
    countries = COUNTRY_CHOICES
    return Response(countries)


@api_view(['GET'])
def ranking_integrity(request):
    """
    Populates ranking for every player in all seasons
    :param request:
    :return:
    """
    response = {}

    players = Player.objects.all()
    for player in players:
        player.create_rankings()
        response[player.id] = f"Ranking verified for player {player.full_name}"

    return Response(response, status=status.HTTP_200_OK)

class PlayerPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 100


class PlayerViewSet(viewsets.ModelViewSet):
    queryset = Player.objects.all().order_by('first_name', 'last_name')
    serializer_class = PlayerSerializer
    pagination_class = PlayerPagination

    def get_permissions(self):
        if self.action in ['create', 'update', 'partial_update', 'destroy']:
            permission_classes = [IsAdminUser]
        else:
            permission_classes = [AllowAny]
        return [permission() for permission in permission_classes]

    # def list(self, request):
    #     pass
    #
    # def create(self, request):
    #     pass
    #
    # def retrieve(self, request, pk=None):
    #     pass
    #
    # def update(self, request, pk=None):
    #     pass
    #
    # def partial_update(self, request, pk=None):
    #     pass
    #
    # def destroy(self, request, pk=None):
    #     pass

class RankingPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 20

class RankingViewSet(viewsets.ModelViewSet):
    queryset = Ranking.objects.all().order_by('-ranking')
    serializer_class = RankingSerializer
    pagination_class = RankingPagination

    def get_permissions(self):
        if self.action in ['create', 'update', 'partial_update', 'destroy']:
            permission_classes = [IsAdminUser]
        else:
            permission_classes = [AllowAny]
        return [permission() for permission in permission_classes]

    def get_queryset(self):
        """
        Get ranking given a season
        :return:
        """
        season = self.request.query_params.get('season_id', None)
        player = self.request.query_params.get('player_id', None)

        ranking = Ranking.objects.all().order_by('-ranking')
        if season and player:
            ranking = Ranking.objects.filter(season=season, player=player).order_by('-ranking')
        elif season:
            ranking = Ranking.objects.filter(season=season).order_by('-ranking')
        elif player:
            ranking = Ranking.objects.filter(player=player).order_by('-ranking')


        print("Returning rankings: ", ranking)

        return ranking

    # def list(self, request):
    #     pass
    #
    # def create(self, request):
    #     pass
    #
    # def retrieve(self, request, pk=None):
    #     pass
    #
    # def update(self, request, pk=None):
    #     pass
    #
    # def partial_update(self, request, pk=None):
    #     pass
    #
    # def destroy(self, request, pk=None):
    #     pass

ttranking/players/templates/players/player_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row align-items-center">
        <div class="col-md-4 text-center">
            {% if player.photo %}
                <img src="{{ player.photo.url }}" alt="{{ player.first_name }} {{ player.last_name }}"
                     class="img-fluid rounded-circle"
                     style="max-width: 80%; height: auto; border: solid 2px #CCCCCC;">
            {% else %}
                <img src="{% static 'players/images/default/player.png' %}" alt="Foto Predeterminada del Jugador" class="img-fluid rounded-circle" style="max-width: 80%; height: auto;">
            {% endif %}
            <h2 class="mt-3">{{ player.first_name }} {{ player.last_name }}</h2>
            {% if player.alias %}
                <h4 class="text-muted fst-italic">{{ player.alias }}</h4>
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card bg-light shadow-sm p-4">
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Fecha de Nacimiento:</strong>
                    </div>
                    <div class="col-sm-8">
                        {{ player.date_of_birth|date:"d M Y" }} ({{ player.age }} años)
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Nacionalidad:</strong>
                    </div>
                    <div class="col-sm-8">
                        {% if player.nationality %}
                            <img src="https://flagsapi.com/{{ player.nationality }}/flat/32.png"
                                 alt="Bandera de {{ player.get_nationality_display }}"
                                 class="img-fluid me-2">
                            {{ player.get_nationality_display }}
                        {% else %}
                            <span class="text-muted">N/D</span>
                        {% endif %}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Ranking Actual:</strong>
                    </div>
                    <div class="col-sm-8">
                        {{ player.ranking }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Partidos Jugados:</strong>
                    </div>
                    <div class="col-sm-8">
                        {{ player.matches_played }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Victorias:</strong>
                    </div>
                    <div class="col-sm-8">
                        {{ player.victories }} ({{ player.winrate }}% winrate)
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-4">
                        <strong>Género:</strong>
                    </div>
                    <div class="col-sm-8">
                        {{ player.get_gender_display }}
                    </div>
                </div>
            </div>
            <a class="btn btn-secondary mt-3" href="{% url 'players:player_list' %}">Volver a la Lista</a>
        </div>
    </div>
</div>
{% endblock %}

ttranking/players/templates/players/player_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Lista de Jugadores</h2>
    <p class="text-muted">Aquí encontrarás la lista de todos los jugadores registrados en el sistema. Puedes ver sus detalles, incluyendo su alias, género, y ranking actual. Haz clic en "Ver Detalles" para obtener más información sobre un jugador específico.</p>

    <!-- Tarjetas de Jugadores -->
    <div class="row">
        {% for player in players %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    {% if player.photo %}
                        <img src="{{ player.photo.url }}" class="card-img-top" alt="{{ player.first_name }} {{ player.last_name }}">
                    {% else %}
                        <img src="{% static 'players/images/default/player.png' %}" class="card-img-top" alt="Jugador Predeterminado">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ player.first_name }} {{ player.last_name }}</h5>
                        <p class="card-text text-muted">{% if player.alias %}{{ player.alias }}{% endif %}</p>
                        <p class="card-text text-muted">{{ player.get_gender_display }}</p>
                        <p class="card-text">Ranking: {{ player.ranking }}</p>
                        <a href="{% url 'players:player_detail' player.id %}" class="btn btn-primary">Ver Detalles</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Controles de Paginación -->
    <div class="pagination">
        <span class="step-links">
            {% if players.has_previous %}
                <a href="?page=1">&laquo; primero</a>
                <a href="?page={{ players.previous_page_number }}">anterior</a>
            {% endif %}

            <span class="current">
                Página {{ players.number }} de {{ players.paginator.num_pages }}.
            </span>

            {% if players.has_next %}
                <a href="?page={{ players.next_page_number }}">siguiente</a>
                <a href="?page={{ players.paginator.num_pages }}">último &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}