ttranking/core/urls.py
# ttranking/core/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.APIRootView.as_view(), name='api_root'),
    path('token/', TokenObtainPairView.as_view(), name='api_token'),
    path('token-refresh/', TokenRefreshView.as_view(), name='api_token_refresh'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('admin/home/', views.AdminHomeView.as_view(), name='admin_home')
]

ttranking/ttranking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler404, handler500
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('api/', include('core.urls')),
    path('api/players/', include('players.urls')),
    path('api/matches/', include('matches.urls')),
    path('api/seasons/', include('seasons.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ttranking/players/models.py
# ttranking/players/models.py
from django.db import models
from django.core.files.base import ContentFile
from datetime import date
from PIL import Image
import io
import os
from uuid import uuid4
from typing import Tuple
from seasons.models import Season

# Define a tuple of tuples with country code and country name
COUNTRY_CHOICES = [
    ('AF', 'Afganistán'),
    ('AL', 'Albania'),
    ('DZ', 'Argelia'),
    ('AO', 'Angola'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaiyán'),
    ('BS', 'Bahamas'),
    ('BH', 'Baréin'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Bielorrusia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belice'),
    ('BJ', 'Benín'),
    ('BT', 'Bután'),
    ('BO', 'Bolivia'),
    ('BA', 'Bosnia y Herzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brasil'),
    ('BN', 'Brunéi'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('KH', 'Camboya'),
    ('CM', 'Camerún'),
    ('CA', 'Canadá'),
    ('CV', 'Cabo Verde'),
    ('CF', 'República Centroafricana'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('KM', 'Comoras'),
    ('CG', 'Congo'),
    ('CD', 'República Democrática del Congo'),
    ('CR', 'Costa Rica'),
    ('CI', 'Costa de Marfil'),
    ('HR', 'Croacia'),
    ('CU', 'Cuba'),
    ('CY', 'Chipre'),
    ('CZ', 'República Checa'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Yibuti'),
    ('DM', 'Dominica'),
    ('DO', 'República Dominicana'),
    ('EC', 'Ecuador'),
    ('EG', 'Egipto'),
    ('SV', 'El Salvador'),
    ('GQ', 'Guinea Ecuatorial'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('ET', 'Etiopía'),
    ('FJ', 'Fiyi'),
    ('FI', 'Finlandia'),
    ('FR', 'Francia'),
    ('GA', 'Gabón'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Alemania'),
    ('GH', 'Ghana'),
    ('GR', 'Grecia'),
    ('GD', 'Granada'),
    ('GT', 'Guatemala'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bisáu'),
    ('GY', 'Guyana'),
    ('HT', 'Haití'),
    ('HN', 'Honduras'),
    ('HU', 'Hungría'),
    ('IS', 'Islandia'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Irán'),
    ('IQ', 'Irak'),
    ('IE', 'Irlanda'),
    ('IL', 'Israel'),
    ('IT', 'Italia'),
    ('JM', 'Jamaica'),
    ('JP', 'Japón'),
    ('JO', 'Jordania'),
    ('KZ', 'Kazajistán'),
    ('KE', 'Kenia'),
    ('KI', 'Kiribati'),
    ('KP', 'Corea del Norte'),
    ('KR', 'Corea del Sur'),
    ('KW', 'Kuwait'),
    ('KG', 'Kirguistán'),
    ('LA', 'Laos'),
    ('LV', 'Letonia'),
    ('LB', 'Líbano'),
    ('LS', 'Lesoto'),
    ('LR', 'Liberia'),
    ('LY', 'Libia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituania'),
    ('LU', 'Luxemburgo'),
    ('MK', 'Macedonia del Norte'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malasia'),
    ('MV', 'Maldivas'),
    ('ML', 'Malí'),
    ('MT', 'Malta'),
    ('MH', 'Islas Marshall'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauricio'),
    ('MX', 'México'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldavia'),
    ('MC', 'Mónaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MA', 'Marruecos'),
    ('MZ', 'Mozambique'),
    ('MM', 'Birmania'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Países Bajos'),
    ('NZ', 'Nueva Zelanda'),
    ('NI', 'Nicaragua'),
    ('NE', 'Níger'),
    ('NG', 'Nigeria'),
    ('NO', 'Noruega'),
    ('OM', 'Omán'),
    ('PK', 'Pakistán'),
    ('PW', 'Palaú'),
    ('PS', 'Territorio Palestino Ocupado'),
    ('PA', 'Panamá'),
    ('PG', 'Papúa Nueva Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Perú'),
    ('PH', 'Filipinas'),
    ('PL', 'Polonia'),
    ('PT', 'Portugal'),
    ('QA', 'Catar'),
    ('RO', 'Rumania'),
    ('RU', 'Federación Rusa'),
    ('RW', 'Ruanda'),
    ('KN', 'San Cristóbal y Nieves'),
    ('LC', 'Santa Lucía'),
    ('VC', 'San Vicente y las Granadinas'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Santo Tomé y Príncipe'),
    ('SA', 'Arabia Saudita'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leona'),
    ('SG', 'Singapur'),
    ('SK', 'Eslovaquia'),
    ('SI', 'Eslovenia'),
    ('SB', 'Islas Salomón'),
    ('SO', 'Somalia'),
    ('ZA', 'Sudáfrica'),
    ('SS', 'Sudán del Sur'),
    ('ES', 'España'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudán'),
    ('SR', 'Surinam'),
    ('SZ', 'Suazilandia'),
    ('SE', 'Suecia'),
    ('CH', 'Suiza'),
    ('SY', 'Siria'),
    ('TW', 'Taiwán'),
    ('TJ', 'Tayikistán'),
    ('TZ', 'Tanzania'),
    ('TH', 'Tailandia'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad y Tobago'),
    ('TN', 'Túnez'),
    ('TR', 'Turquía'),
    ('TM', 'Turkmenistán'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ucrania'),
    ('AE', 'Emiratos Árabes Unidos'),
    ('GB', 'Reino Unido'),
    ('US', 'Estados Unidos'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistán'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabue'),
]

GENDER_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Femenino')
]

DESIRED_SIZE = (600, 600)

def get_image_upload_path(instance, filename):
    # Generate a new filename using the player's ID or a UUID
    if not filename:
        return None
    ext = instance.photo.name.split('.')[-1]
    new_filename = f'{instance.id or uuid4().hex}.{ext}'
    return os.path.join('player_photos/', new_filename)

class Player(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=False, blank=True, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=2, choices=COUNTRY_CHOICES, blank=True, null=True)
    photo = models.ImageField(upload_to=get_image_upload_path, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    @property
    def age(self) -> int:
        if self.date_of_birth is None:
            return None
        today = date.today()
        age = today.year - self.date_of_birth.year
        if (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day):
            age -= 1
        return age

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Step 1: Check if this is an update and get the old instance
        if self.pk:
            old_instance = Player.objects.filter(pk=self.pk).first()
            old_photo = old_instance.photo if old_instance else None
        else:
            old_photo = None

        # Step 2: Process the new photo only if it's updated
        if self.photo and (not old_photo or old_photo != self.photo):
            # Delete the old photo if a new one is being uploaded
            if old_photo and os.path.isfile(old_photo.path):
                os.remove(old_photo.path)

            # Generate a new unique path for the photo
            ext = self.photo.name.split('.')[-1]
            file_path = os.path.join('player_photos/', f'{uuid4().hex}.{ext}')

            # Open and process the image
            image = Image.open(self.photo)
            image = self.resize_and_crop(image, DESIRED_SIZE)

            # Save the processed image to a BytesIO object
            buffer = io.BytesIO()
            image.save(buffer, format='PNG')
            buffer.seek(0)

            # Save the resized image to the photo field
            self.photo.save(file_path, ContentFile(buffer.read()), save=False)

        # Step 3: Call the original save method to save the rest of the fields
        super(Player, self).save(*args, **kwargs)

        self.create_rankings()

    def create_rankings(self):
        # Step 4: Create the player rankings for all seasons
        Ranking.populate_ranking(self)

    def resize_and_crop(self, image, size):
        # Resize the image without preserving the aspect ratio
        image = image.convert('RGBA')
        image = image.resize(size)
        return image

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Ranking(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='season_rankings')
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='player_rankings')
    ranking = models.IntegerField(default=0)
    singles_matches_played = models.IntegerField(default=0)
    doubles_matches_played = models.IntegerField(default=0)
    doubles_victories = models.IntegerField(default=0)
    singles_victories = models.IntegerField(default=0)

    class Meta:
        unique_together = ('player', 'season')

    @property
    def matches_played(self):
        return self.singles_matches_played + self.doubles_matches_played

    @property
    def victories(self):
        return self.doubles_victories + self.singles_victories

    @property
    def winrate(self):
        if self.matches_played == 0:
            return 0
        return round((self.victories / self.matches_played) * 100, 2)

    def get_season_points(self, match_type: str) -> Tuple[int, int]:
        """
        Get the points for a win and a loss correspoding to the season assigned for the given match type
        (singles or doubles)
        :param match_type:
        :return:
        """
        if match_type not in ['singles', 'doubles']:
            raise ValueError("Invalid match type, must be 'singles' or 'doubles'")

        season = self.season
        if match_type == 'singles':
            return season.singles_points_for_win, season.singles_points_for_loss
        elif match_type == 'doubles':

ttranking/core/views.py
# ttranking/core/views.py
from datetime import timezone

from django.http import HttpResponseServerError, HttpResponseNotFound
from django.shortcuts import render
from django.db import models
from django.template import loader

from django.utils import timezone

from players.models import Player, Ranking
from players.serializers import PlayerSerializer, RankingSerializer

from matches.models import SinglesMatch, DoublesMatch
from matches.serializers import SinglesMatchSerializer, DoublesMatchSerializer

from seasons.models import Season
from seasons.serializers import SeasonSerializer


from django.urls import reverse

from rest_framework.permissions import IsAuthenticatedOrReadOnly, AllowAny, IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import TokenAuthentication



class APIRootView(APIView):
    """
    API root view
    """
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get(self, request):
        return Response({
            'players': reverse('players:player-list'),
            'singles_matches': reverse('matches:singlesmatch-list'),
            'doubles_matches': reverse('matches:doublesmatch-list'),
            'seasons': reverse('seasons:season-list'),
        })

class HomeView(APIView):
    permission_classes = [AllowAny]

    def order_by_winrate(self, queryset):
        return sorted(queryset, key=lambda x: x.winrate, reverse=True)

    def get(self, request):
        current_season = Season.get_season_for_datetime(timezone.make_aware(timezone.datetime.now()))

        if not current_season:
            return Response({
                'matchesPlayed': 0,
                'currentSeason': None,
                'topPlayers': [],
                'topByWinrate': [],
                'ranking': [],
            })

        print(Ranking.objects.all())

        ranking = Ranking.objects.filter(season=current_season).order_by('-ranking')

        top = ranking[:3]

        top_winrate = self.order_by_winrate(ranking)[:6]

        matches_played = 0
        for _ in SinglesMatch.objects.filter(season=current_season):
            matches_played += 1

        for _ in DoublesMatch.objects.filter(season=current_season):
            matches_played += 1

        data = {
            'matchesPlayed': matches_played,
            'currentSeason': SeasonSerializer(current_season).data,
            'topPlayers': RankingSerializer(top, many=True).data,
            'topByWinrate': RankingSerializer(top_winrate, many=True).data,
            'ranking': RankingSerializer(ranking[:20], many=True).data,
        }

        return Response(data)

class AdminHomeView(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        # Number of registered players
        registered_players = Player.objects.all().count()

        # Timeframe calculations
        now = timezone.make_aware(timezone.datetime.now())
        three_days_ago = now - timezone.timedelta(days=3)
        one_week_ago = now - timezone.timedelta(days=7)

        # Single matches played in the last 3 days
        single_matches_played_last_3days = SinglesMatch.objects.filter(date__gte=three_days_ago).count()

        # Double matches played in the last 3 days
        double_matches_played_last_3days = DoublesMatch.objects.filter(date__gte=three_days_ago).count()

        # Most active players in the last week
        singles_matches_last_week = (
            SinglesMatch.objects.filter(date__gte=one_week_ago)
            .values('player1', 'player2')
            .annotate(matches_played=models.Count('id'))
        )
        doubles_matches_last_week = (
            DoublesMatch.objects.filter(date__gte=one_week_ago)
            .values('team1_player1', 'team1_player2', 'team2_player1', 'team2_player2')
            .annotate(matches_played=models.Count('id'))
        )

        # Aggregate matches for each player
        player_match_counts = {}
        for entry in singles_matches_last_week:
            for player in ['player1', 'player2']:
                player_match_counts[entry[player]] = player_match_counts.get(entry[player], 0) + entry['matches_played']

        for entry in doubles_matches_last_week:
            for player in ['team1_player1', 'team1_player2', 'team2_player1', 'team2_player2']:
                player_match_counts[entry[player]] = player_match_counts.get(entry[player], 0) + entry['matches_played']

        most_active_players_last_week = sorted(player_match_counts.items(), key=lambda x: x[1], reverse=True)[:5]

        # Prepare response data
        data = {
            "registered_players": registered_players,
            "single_matches_played_last_3days": single_matches_played_last_3days,
            "double_matches_played_last_3days": double_matches_played_last_3days,
            "most_active_players_last_week": [
                {
                    "player_name": Player.objects.get(id=player_id).full_name,
                    "matches_played_last_week": matches_played,
                }
                for player_id, matches_played in most_active_players_last_week
            ],
        }

        return Response(data)

ttranking/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Clasificación Tenis de Mesa{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/favicon.ico' %}">
    <!-- Tailwind CSS (Via CDN) -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
</head>
<body class="bg-gray-100">

    <!-- Navbar -->
    <header class="sticky top-0 z-50 w-full bg-primary-color py-3 px-4 sm:px-10">
        <div class="flex justify-between items-center">
            <a href="{% url 'core:home' %}" class="flex items-center text-white no-underline">
                <img src="{% static 'core/images/logo-white-48.png' %}" alt="Logo" class="h-12"/>
                <span class="text-2xl ml-2">Clasificación de Tenis de Mesa</span>
            </a>
            <!-- Mobile Hamburger Icon -->
            <button class="sm:hidden text-white" id="navbar-toggle">
                <i class="fas fa-bars"></i>
            </button>
            <!-- Navbar Links (Hidden on mobile) -->
            <ul class="hidden sm:flex space-x-4 sm:space-x-8 text-sm sm:text-base" id="navbar-links">
                <li><a href="{% url 'core:home' %}" class="nav-link text-neutral-50 {% if request.resolver_match.url_name == 'home' %}font-bold text-white{% endif %}">Inicio</a></li>
                <li><a href="{% url 'players:player_list' %}" class="nav-link text-neutral-50 {% if request.resolver_match.url_name == 'players:player_list' %}font-bold text-white{% endif %}">Jugadores</a></li>
                <li><a href="{% url 'matches:match_list' %}" class="nav-link text-neutral-50 {% if request.resolver_match.url_name == 'matches:match_list' %}font-bold text-white{% endif %}">Partidos</a></li>
                <li>
                    <a href="{% url 'seasons:season_list' %}" class="nav-link text-neutral-50 {% if request.resolver_match.url_name == 'core:seasons' %}font-bold text-white{% endif %}">Temporadas</a>
                </li>

                <li>
                    <a href="{% url 'admin_panel:login' %}" class="text-white bg-transparent border-2 border-white rounded py-2 px-4 hover:bg-white hover:text-primary-color transition-colors">Iniciar Sesión</a>
                </li>
            </ul>
        </div>
    </header>

    <!-- Hero Section -->
    <section class="hero-section bg-primary-color text-white text-center">
        {% block hero %}
        <!-- Hero section content -->
        {% endblock %}
    </section>

    <!-- Main Content Area -->
    <main class="container mx-auto mt-4 px-4 sm:px-8">
        {% block content %}
        <!-- Page-specific content -->
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="bg-gray-900 text-white py-8">
        <div class="container mx-auto px-4 sm:px-8">
            <!-- Footer Content Section -->
            <div class="flex flex-wrap justify-between sm:justify-evenly text-sm mb-6">
                <!-- Developed By Section -->
                <div class="w-full sm:w-auto text-center sm:text-left mb-4 sm:mb-0">
                    <h6 class="font-bold uppercase mb-2">Desarrollado por Juan Sobalvarro</h6>
                    <p>Sistema de Clasificación de Tenis de Mesa</p>
                </div>

                <!-- Contact Section -->
                <div class="w-full sm:w-auto text-center sm:text-left mb-4 sm:mb-0">
                    <h6 class="font-bold uppercase mb-2">Contacto</h6>
                    <p>Email: <a href="mailto:sobalvarrog.juans@gmail.com" class="underline">sobalvarrog.juans@gmail.com</a></p>
                    <p>Email: <a href="mailto:juan.sobalvarro@est.ulsa.edu.ni" class="underline">juan.sobalvarro@est.ulsa.edu.ni</a></p>
                </div>

                <!-- Social Media Section -->
                <div class="w-full sm:w-auto text-center sm:text-left">
                    <h6 class="font-bold uppercase mb-2">Sígueme</h6>
                    <div class="flex justify-center sm:justify-start">
                        <a href="https://github.com/JuanSobalvarro" target="_blank" class="mr-4 text-xl">
                            <i class="fab fa-github"></i>
                        </a>
                        <a href="https://x.com/JuanSobalvarroG" target="_blank" class="text-xl">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Footer Bottom Section -->
            <div class="text-center py-2 border-t border-gray-700 mt-6">
                <a href="https://github.com/JuanSobalvarro/tt-ranking-system" class="text-white text-sm">
                    © 2024 Sistema de Clasificación de Tenis de Mesa
                </a>
            </div>
        </div>
    </footer>


    <!-- JavaScript -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var currentPath = window.location.pathname;
            var navLinks = document.querySelectorAll('.nav-link');

            navLinks.forEach(function(link) {
                if (link.getAttribute('href') === currentPath) {
                    link.classList.add('font-bold', 'text-white');
                }
            });
        });

        // Mobile Navbar Toggle Script
        document.getElementById('navbar-toggle').addEventListener('click', function () {
            const navbarLinks = document.getElementById('navbar-links');
            navbarLinks.classList.toggle('hidden');
        });

        // Tailwind-Compatible Modal (Using Alpine.js or your custom JS if needed)
        {% if messages %}
            document.addEventListener('DOMContentLoaded', function() {
                const modalContent = `
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                `;
                alert(modalContent); // Example using a simple alert for now, you could integrate Alpine.js for better modal behavior
            });
        {% endif %}
    </script>

    {% block scripts %}
    <!-- Additional page-specific scripts -->
    {% endblock %}
</body>
</html>

ttranking/core/templates/core/base_error.html
<!-- ttranking/core/templates/core/error_base.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Error{% endblock %}</title>
    <!-- <link rel="stylesheet" href="{% static 'core/css/styles.css' %}"> -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            color: #333;
            text-align: center;
        }

        header, footer {
            background-color: #333;
            color: white;
            padding: 10px 0;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin: 0 15px;
        }

        nav ul li a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }

        main {
            padding: 50px 20px;
        }

        h1 {
            font-size: 2.5em;
            color: #007bff;
        }

        p {
            font-size: 1.2em;
        }

        a {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 20px;
            color: white;
            background-color: #007bff;
            text-decoration: none;
            border-radius: 5px;
        }

        a:hover {
            background-color: #0056b3;
        }

    </style>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Inicio</a></li>
                <li><a href="{% url 'match_list' %}">Partidos</a></li>
                <li><a href="{% url 'player_list' %}">Jugadores</a></li>
                <!-- Agregar más enlaces según sea necesario -->
            </ul>
        </nav>
    </header>

    <main>
        <h1>{% block error_code %}Error{% endblock %}</h1>
        <p>{% block error_message %}Ocurrió un error inesperado.{% endblock %}</p>
        <a href="{% url 'home' %}">Volver a la página principal</a>
    </main>

    <footer>
        <p>&copy; 2024 Sistema de Clasificación de Tenis de Mesa. Todos los derechos reservados.</p>
    </footer>
</body>
</html>